### ISSUE TITLE
TODO for initial release

### ISSUE THREAD

**Issue by onsd** [wantedly/resource-name-sanitizer#1]
## Why
In order to release resource-name-sanitizer, we will need to perform a number of functions.

resource-name-sanitizer has features like bellow
- convert to valid strings from any strings
	-  the user can decide what is a valid string by setting the regex pattern
	- also the user can set limits of length of the string

## What
Implement to achieve the features.

### TODO
- [x] set pattern for validation https://github.com/wantedly/resource-name-sanitizer/pull/2
- [x] set max length of string https://github.com/wantedly/resource-name-sanitizer/pull/2
- [x] check if a given string is valid for pattern  https://github.com/wantedly/resource-name-sanitizer/pull/2
- [x] sanitize a given string to a valid string
- [ ] ~~get multi strings and generate valid string~~

**Comment by onsd** [comment]
done!
